[package]
name = "p2p_panel"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/p2p_panel.rs"

[dependencies]
anyhow.workspace = true
db.workspace = true
gpui.workspace = true
serde.workspace = true
serde_json.workspace = true
util.workspace = true
workspace.workspace = true
# willow-store-simple-sled = "0.1"
# willow_25 = "0.1"
willow-store-simple-sled.path = "../../../../earthstar-project/willow-rs/store_simple_sled"
willow_25.path = "../../../../earthstar-project/willow-rs/willow_25"
sled = "0.34.7"

[lints]
workspace = true
